/**
 * @see Original module
 * {@link https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts}
 * {@link file://./../../node_modules/obsidian/obsidian.d.ts}
 */
import "obsidian";

import "./AbstractInputSuggest.d.ts";
import "./AbstractTextComponent.d.ts";
import "./App.d.ts";
import "./BaseComponent.d.ts";
import "./BlockCache.d.ts";
import "./BlockSubpathResult.d.ts";
import "./ButtonComponent.d.ts";
import "./CachedMetadata.d.ts";
import "./CacheItem.d.ts";
import "./CloseableComponent.d.ts";
import "./ColorComponent.d.ts";
import "./Command.d.ts";
import "./Component.d.ts";
import "./DataAdapter.d.ts";
import "./DataWriteOptions.d.ts";
import "./Debouncer.d.ts";
import "./DropdownComponent.d.ts";
import "./EditableFileView.d.ts";
import "./Editor.d.ts";
import "./EditorChange.d.ts";
import "./EditorPosition.d.ts";
import "./EditorRange.d.ts";
import "./EditorRangeOrCaret.d.ts";
import "./EditorScrollInfo.d.ts";
import "./EditorSelection.d.ts";
import "./EditorSelectionOrCaret.d.ts";
import "./EditorSuggest.d.ts";
import "./EditorSuggestContext.d.ts";
import "./EditorSuggestTriggerInfo.d.ts";
import "./EditorTransaction.d.ts";
import "./EmbedCache.d.ts";
import "./EventRef.d.ts";
import "./Events.d.ts";
import "./ExtraButtonComponent.d.ts";
import "./FileManager.d.ts";
import "./FileStats.d.ts";
import "./FileSystemAdapter.d.ts";
import "./FileView.d.ts";
import "./FrontMatterCache.d.ts";
import "./FrontMatterInfo.d.ts";
import "./FrontmatterLinkCache.d.ts";
import "./FuzzyMatch.d.ts";
import "./FuzzySuggestModal.d.ts";
import "./HeadingCache.d.ts";
import "./HeadingSubpathResult.d.ts";
import "./Hotkey.d.ts";
import "./HoverLinkSource.d.ts";
import "./HoverParent.d.ts";
import "./HoverPopover.d.ts";
import "./HSL.d.ts";
import "./Instruction.d.ts";
import "./ISuggestOwner.d.ts";
import "./ItemView.d.ts";
import "./Keymap.d.ts";
import "./KeymapContext.d.ts";
import "./KeymapEventHandler.d.ts";
import "./KeymapInfo.d.ts";
import "./LinkCache.d.ts";
import "./ListedFiles.d.ts";
import "./ListItemCache.d.ts";
import "./LivePreviewState.d.ts";
import "./Loc.d.ts";
import "./MarkdownEditView.d.ts";
import "./MarkdownFileInfo.d.ts";
import "./MarkdownPostProcessor.d.ts";
import "./MarkdownPostProcessorContext.d.ts";
import "./MarkdownPreviewEvents.d.ts";
import "./MarkdownPreviewRenderer.d.ts";
import "./MarkdownPreviewView.d.ts";
import "./MarkdownRenderChild.d.ts";
import "./MarkdownRenderer.d.ts";
import "./MarkdownSectionInformation.d.ts";
import "./MarkdownSubView.d.ts";
import "./MarkdownView.d.ts";
import "./Menu.d.ts";
import "./MenuItem.d.ts";
import "./MenuPositionDef.d.ts";
import "./MenuSeparator.d.ts";
import "./MetadataCache.d.ts";
import "./Modal.d.ts";
import "./MomentFormatComponent.d.ts";
import "./Notice.d.ts";
import "./ObsidianProtocolData.d.ts";
import "./OpenViewState.d.ts";
import "./Platform.d.ts";
import "./Plugin.d.ts";
import "./PluginManifest.d.ts";
import "./PluginSettingTab.d.ts";
import "./Point.d.ts";
import "./PopoverSuggest.d.ts";
import "./Pos.d.ts";
import "./PreparedQuery.d.ts";
import "./ProgressBarComponent.d.ts";
import "./Reference.d.ts";
import "./ReferenceCache.d.ts";
import "./RequestUrlParam.d.ts";
import "./RequestUrlResponse.d.ts";
import "./RequestUrlResponsePromise.d.ts";
import "./RGB.d.ts";
import "./Scope.d.ts";
import "./SearchComponent.d.ts";
import "./SearchResult.d.ts";
import "./SearchResultContainer.d.ts";
import "./SectionCache.d.ts";
import "./Setting.d.ts";
import "./SettingTab.d.ts";
import "./SliderComponent.d.ts";
import "./Stat.d.ts";
import "./SubpathResult.d.ts";
import "./SuggestModal.d.ts";
import "./TAbstractFile.d.ts";
import "./TagCache.d.ts";
import "./Tasks.d.ts";
import "./TextAreaComponent.d.ts";
import "./TextComponent.d.ts";
import "./TextFileView.d.ts";
import "./TFile.d.ts";
import "./TFolder.d.ts";
import "./ToggleComponent.d.ts";
import "./TooltipOptions.d.ts";
import "./ValueComponent.d.ts";
import "./Vault.d.ts";
import "./View.d.ts";
import "./ViewState.d.ts";
import "./ViewStateResult.d.ts";
import "./Workspace.d.ts";
import "./WorkspaceContainer.d.ts";
import "./WorkspaceFloating.d.ts";
import "./WorkspaceItem.d.ts";
import "./WorkspaceLeaf.d.ts";
import "./WorkspaceMobileDrawer.d.ts";
import "./WorkspaceParent.d.ts";
import "./WorkspaceRibbon.d.ts";
import "./WorkspaceRoot.d.ts";
import "./WorkspaceSidedock.d.ts";
import "./WorkspaceSplit.d.ts";
import "./WorkspaceTabs.d.ts";
import "./WorkspaceWindow.d.ts";
import "./WorkspaceWindowInitData.d.ts";

export * from "./implementations/index.ts";

export type { AbstractSearchComponent } from "./internals/AbstractSearchComponent.d.ts";
export type { Account } from "./internals/Account.d.ts";
export type { AppMenuBarManager } from "./internals/AppMenuBarManager.d.ts";
export type { AppVaultConfig } from "./internals/AppVaultConfig.d.ts";
export type { BaseEditor } from "./internals/BaseEditor.d.ts";
export type { CanvasConnection } from "./internals/CanvasConnection.d.ts";
export type { CanvasLeaf } from "./internals/CanvasLeaf.d.ts";
export type { CanvasNode } from "./internals/CanvasNode.d.ts";
export type { CanvasView } from "./internals/CanvasView.d.ts";
export type { ClipBoardManager } from "./internals/ClipBoardManager.d.ts";
export type { Commands } from "./internals/Commands.d.ts";
export type { ConfigItem } from "./internals/ConfigItem.d.ts";
export type { CustomArrayDict } from "./internals/CustomArrayDict.d.ts";
export type { CustomCSS } from "./internals/CustomCSS.d.ts";
export type { DragManager } from "./internals/DragManager.d.ts";
export type { EditorSearchComponent } from "./internals/EditorSearchComponent.d.ts";
export type { EditorSuggests } from "./internals/EditorSuggests.d.ts";
export type { EmbedContext } from "./internals/EmbedContext.d.ts";
export type { EmbeddableConstructor } from "./internals/EmbeddableConstructor.d.ts";
export type { EmbeddedEditorView } from "./internals/EmbeddedEditorView.d.ts";
export type { EmbedRegistry } from "./internals/EmbedRegistry.d.ts";
export type { FileCacheEntry } from "./internals/FileCacheEntry.d.ts";
export type { FileEntry } from "./internals/FileEntry.d.ts";
export type { FileExplorerLeaf } from "./internals/FileExplorerLeaf.d.ts";
export type { FileExplorerView } from "./internals/FileExplorerView.d.ts";
export type { FileSuggest } from "./internals/FileSuggest.d.ts";
export type { FileSuggestManager } from "./internals/FileSuggestManager.d.ts";
export type { FileTreeItem } from "./internals/FileTreeItem.d.ts";
export type { FoldInfo } from "./internals/FoldInfo.d.ts";
export type { FoldManager } from "./internals/FoldManager.d.ts";
export type { FootnoteCache } from "./internals/FootnoteCache.d.ts";
export type { GlobalSearchLeaf } from "./internals/GlobalSearchLeaf.d.ts";
export type { HotkeyManager } from "./internals/HotkeyManager.d.ts";
export type { HoverLinkEvent } from "./internals/HoverLinkEvent.d.ts";
export type { IFramedMarkdownEditor } from "./internals/IFramedMarkdownEditor.d.ts";
export type { ImportedAttachments } from "./internals/ImportedAttachments.d.ts";
export type { InfinityScroll } from "./internals/InfinityScroll.d.ts";
export type { InternalPlugin } from "./internals/InternalPlugin.d.ts";
export type { KeyScope } from "./internals/KeyScope.d.ts";
export type { LeafEntry } from "./internals/LeafEntry.d.ts";
export type { LinkUpdate } from "./internals/LinkUpdate.d.ts";
export type { LoadProgress } from "./internals/LoadProgress.d.ts";
export type { MarkdownBaseView } from "./internals/MarkdownBaseView.d.ts";
export type { MarkdownScrollableEditView } from "./internals/MarkdownScrollableEditView.d.ts";
export type { MetadataEditor } from "./internals/MetadataEditor.d.ts";
export type { MetadataEditorProperty } from "./internals/MetadataEditorProperty.d.ts";
export type { MetadataTypeManager } from "./internals/MetadataTypeManager.d.ts";
export type { MetadataWidget } from "./internals/MetadataWidget.d.ts";
export type { MobileNavbar } from "./internals/MobileNavbar.d.ts";
export type { MobileToolbar } from "./internals/MobileToolbar.d.ts";
export type { ObsidianDOM } from "./internals/ObsidianDOM.d.ts";
export type { ObsidianTouchEvent } from "./internals/ObsidianTouchEvent.d.ts";
export type { Plugins } from "./internals/Plugins.d.ts";
export type { PluginUpdateManifest } from "./internals/PluginUpdateManifest.d.ts";
export type { PositionedReference } from "./internals/PositionedReference.d.ts";
export type { PropertyEntryData } from "./internals/PropertyEntryData.d.ts";
export type { PropertyInfo } from "./internals/PropertyInfo.d.ts";
export type { PropertyRenderContext } from "./internals/PropertyRenderContext.d.ts";
export type { PropertyWidget } from "./internals/PropertyWidget.d.ts";
export type { PropertyWidgetType } from "./internals/PropertyWidgetType.d.ts";
export type { ReadViewRenderer } from "./internals/ReadViewRenderer.d.ts";
export type { RecentFileTracker } from "./internals/RecentFileTracker.d.ts";
export type { RendererSection } from "./internals/RendererSection.d.ts";
export type { Runnable } from "./internals/Runnable.d.ts";
export type { SearchCursor } from "./internals/SearchCursor.d.ts";
export type { SerializedWorkspace } from "./internals/SerializedWorkspace.d.ts";
export type { StateHistory } from "./internals/StateHistory.d.ts";
export type { SuggestionContainer } from "./internals/SuggestionContainer.d.ts";
export type { TableCell } from "./internals/TableCell.d.ts";
export type { TableCellEditor } from "./internals/TableCellEditor.d.ts";
export type { TableEditor } from "./internals/TableEditor.d.ts";
export type { ThemeManifest } from "./internals/ThemeManifest.d.ts";
export type { Token } from "./internals/Token.d.ts";
export type { Tree } from "./internals/Tree.d.ts";
export type { TreeItem } from "./internals/TreeItem.d.ts";
export type { TreeNode } from "./internals/TreeNode.d.ts";
export type { ViewRegistry } from "./internals/ViewRegistry.d.ts";
export type { WeakMapWrapper } from "./internals/WeakMapWrapper.d.ts";
export type { WidgetEditorView } from "./internals/WidgetEditorView.d.ts";
export type { WindowSelection } from "./internals/WindowSelection.d.ts";

/**
 * @note @see {@link file://./../../index.d.ts}
 */
export * from "./internals/InternalPlugin.ts";
