/**
 * @todo Documentation incomplete
 *
 * @public
 * @unofficial
 */
export type ConfigItem =
    | 'accentColor'
    | 'alwaysUpdateLinks'
    | 'attachmentFolderPath'
    | 'autoConvertHtml'
    | 'autoPairBrackets'
    | 'autoPairMarkdown'
    | 'baseFontSize'
    | 'baseFontSizeAction'
    | 'cssTheme'
    | 'defaultViewMode'
    | 'enabledCssSnippets'
    | 'focusNewTab'
    | 'foldHeading'
    | 'foldIndent'
    | 'hotkeys'
    | 'interfaceFontFamily'
    | 'livePreview'
    | 'mobilePullAction'
    | 'mobileQuickRibbonItem'
    | 'mobileToolbarCommands'
    | 'monospaceFontFamily'
    | 'nativeMenus'
    | 'newFileFolderPath'
    | 'newFileLocation'
    | 'newLinkFormat'
    | 'pdfExportSettings'
    | 'promptDelete'
    | 'propertiesInDocument'
    | 'readableLineLength'
    | 'rightToLeft'
    | 'showIndentGuide'
    | 'showInlineTitle'
    | 'showLineNumber'
    | 'showRibbon'
    | 'showUnsupportedFiles'
    | 'showViewHeader'
    | 'smartIndentList'
    | 'spellcheck'
    | 'spellcheckLanguages'
    | 'strictLineBreaks'
    | 'tabSize'
    | 'textFontFamily'
    | 'theme'
    | 'translucency'
    | 'trashOption'
    | 'types'
    | 'uriCallbacks'
    | 'useMarkdownLinks'
    | 'useTab'
    | 'userIgnoreFilters'
    | 'vimMode';
