import type { ViewType } from '../../implementations/ViewType.ts';
import type { BrowserHistoryView } from '../Views/BrowserHistoryView.js';
import type { AllPropertiesView } from '../InternalPlugins/Properties/AllPropertiesView.js';
import type { TypedWorkspaceLeaf } from './TypedWorkspaceLeaf.js';
import type { AudioView } from '../Views/AudioView.js';
import type { BacklinkView } from '../InternalPlugins/Backlink/BacklinkView.js';
import type { BookmarksView } from '../InternalPlugins/Bookmarks/BookmarksView.js';
import type { BrowserView } from '../Views/BrowserView.js';
import type { CanvasView } from '../InternalPlugins/Canvas/CanvasView.js';
import type { EmptyView } from '../Views/EmptyView.js';
import type { FileExplorerView } from '../InternalPlugins/FileExplorer/FileExplorerView.js';
import type { FilePropertiesView } from '../InternalPlugins/Properties/FilePropertiesView.js';
import type { GraphView } from '../InternalPlugins/Graph/GraphView.js';
import type { LocalGraphView } from '../InternalPlugins/Graph/LocalGraphView.js';
import type { OutgoingLinkView } from '../InternalPlugins/OutgoingLink/OutgoingLinkView.js';
import type { ImageView } from '../Views/ImageView.js';
import type { OutlineView } from '../InternalPlugins/Outline/OutlineView.js';
import type { MarkdownView } from 'obsidian';
import type { PdfView } from '../Views/PdfView.js';
import type { ReleaseNotesView } from '../Views/ReleaseNotesView.js';
import type { SearchView } from '../InternalPlugins/GlobalSearch/SearchView.js';
import type { TagView } from '../Views/TagView.js';
import type { VideoView } from '../Views/VideoView.js';

/** @public */
export type ViewTypeLeafMapping = {
    [ViewType.AllProperties]: TypedWorkspaceLeaf<AllPropertiesView>;
    [ViewType.Audio]: TypedWorkspaceLeaf<AudioView>;
    [ViewType.Backlink]: TypedWorkspaceLeaf<BacklinkView>;
    [ViewType.Bookmarks]: TypedWorkspaceLeaf<BookmarksView>;
    [ViewType.Browser]: TypedWorkspaceLeaf<BrowserView>;
    [ViewType.BrowserHistory]: TypedWorkspaceLeaf<BrowserHistoryView>;
    [ViewType.Canvas]: TypedWorkspaceLeaf<CanvasView>;
    [ViewType.Empty]: TypedWorkspaceLeaf<EmptyView>;
    [ViewType.FileExplorer]: TypedWorkspaceLeaf<FileExplorerView>;
    [ViewType.FileProperties]: TypedWorkspaceLeaf<FilePropertiesView    >;
    [ViewType.Graph]: TypedWorkspaceLeaf<GraphView>;
    [ViewType.Image]: TypedWorkspaceLeaf<ImageView>;
    [ViewType.LocalGraph]: TypedWorkspaceLeaf<LocalGraphView>;
    [ViewType.Markdown]: TypedWorkspaceLeaf<MarkdownView>;
    [ViewType.OutgoingLink]: TypedWorkspaceLeaf<OutgoingLinkView>;
    [ViewType.Outline]: TypedWorkspaceLeaf<OutlineView>;
    [ViewType.Pdf]: TypedWorkspaceLeaf<PdfView>;
    [ViewType.ReleaseNotes]: TypedWorkspaceLeaf<ReleaseNotesView>;
    [ViewType.Search]: TypedWorkspaceLeaf<SearchView>;
    [ViewType.Tag]: TypedWorkspaceLeaf<TagView>;
    [ViewType.Video]: TypedWorkspaceLeaf<VideoView>;
};
