import type { AudioRecorderPlugin } from './AudioRecorderPlugin.js';
import type { BacklinkPlugin } from './BacklinkPlugin.js';
import type { BookmarksPlugin } from './BookmarksPlugin.js';
import type { CanvasPlugin } from './CanvasPlugin.js';
import type { CommandPalettePlugin } from './CommandPalettePlugin.js';
import type { DailyNotesPlugin } from './DailyNotesPlugin.js';
import type { EditorStatusPlugin } from './EditorStatusPlugin.js';
import type { FileExplorerPlugin } from './FileExplorerPlugin.js';
import type { FileRecoveryPlugin } from './FileRecoveryPlugin.js';
import type { GlobalSearchPlugin } from './GlobalSearchPlugin.js';
import type { GraphPlugin } from './GraphPlugin.js';
import type { InternalPluginName } from './InternalPluginName.js';
import type { MarkdownImporterPlugin } from './MarkdownImporterPlugin.js';
import type { NoteComposerPlugin } from './NoteComposerPlugin.js';
import type { OutgoingLinkPlugin } from './OutgoingLinkPlugin.js';
import type { OutlinePlugin } from './OutlinePlugin.js';
import type { PagePreviewPlugin } from './PagePreviewPlugin.js';
import type { PropertiesPlugin } from './PropertiesPlugin.js';
import type { PublishPlugin } from './PublishPlugin.js';
import type { RandomNotePlugin } from './RandomNotePlugin.js';
import type { SlashCommandPlugin } from './SlashCommandPlugin.js';
import type { SlidesPlugin } from './SlidesPlugin.js';
import type { SwitcherPlugin } from './SwitcherPlugin.js';
import type { SyncPlugin } from './SyncPlugin.js';
import type { TagPanePlugin } from './TagPanePlugin.js';
import type { TemplatesPlugin } from './TemplatesPlugin.js';
import type { WordCountPlugin } from './WordCountPlugin.js';
import type { WorkspacesPlugin } from './WorkspacesPlugin.js';
import type { ZkPrefixerPlugin } from './ZkPrefixerPlugin.js';

/** @public */
export type InternalPluginNamePluginsMapping = {
    [InternalPluginName.AudioRecorder]: AudioRecorderPlugin;
    [InternalPluginName.Backlink]: BacklinkPlugin;
    [InternalPluginName.Bookmarks]: BookmarksPlugin;
    [InternalPluginName.Canvas]: CanvasPlugin;
    [InternalPluginName.CommandPalette]: CommandPalettePlugin;
    [InternalPluginName.DailyNotes]: DailyNotesPlugin;
    [InternalPluginName.EditorStatus]: EditorStatusPlugin;
    [InternalPluginName.FileExplorer]: FileExplorerPlugin;
    [InternalPluginName.FileRecovery]: FileRecoveryPlugin;
    [InternalPluginName.GlobalSearch]: GlobalSearchPlugin;
    [InternalPluginName.Graph]: GraphPlugin;
    [InternalPluginName.MarkdownImporter]: MarkdownImporterPlugin;
    [InternalPluginName.NoteComposer]: NoteComposerPlugin;
    [InternalPluginName.OutgoingLink]: OutgoingLinkPlugin;
    [InternalPluginName.Outline]: OutlinePlugin;
    [InternalPluginName.PagePreview]: PagePreviewPlugin;
    [InternalPluginName.Properties]: PropertiesPlugin;
    [InternalPluginName.Publish]: PublishPlugin;
    [InternalPluginName.RandomNote]: RandomNotePlugin;
    [InternalPluginName.SlashCommand]: SlashCommandPlugin;
    [InternalPluginName.Slides]: SlidesPlugin;
    [InternalPluginName.Switcher]: SwitcherPlugin;
    [InternalPluginName.Sync]: SyncPlugin;
    [InternalPluginName.TagPane]: TagPanePlugin;
    [InternalPluginName.Templates]: TemplatesPlugin;
    [InternalPluginName.WordCount]: WordCountPlugin;
    [InternalPluginName.Workspaces]: WorkspacesPlugin;
    [InternalPluginName.ZkPrefixer]: ZkPrefixerPlugin;
};
