export {};

declare module 'obsidian' {
    /**
     * The cache of the section in the note.
     * Sections are root level markdown blocks, which can be used to divide the document up.
     *
     * ```markdown
     * # Heading section
     *
     * Paragraph section
     *
     * > [!NOTE]
     * > Callout section
     * ```
     */
    interface SectionCache extends CacheItem {
        /**
         * The block ID of this section, if defined.
         *
         * @official
         */
        id?: string | undefined;

        /**
         * The type string generated by the parser.
         * Typing is non-exhaustive, more types can be available than are documented here.
         *
         * @official
         */
        type:
            | 'blockquote'
            | 'callout'
            | 'code'
            | 'element'
            | 'footnoteDefinition'
            | 'heading'
            | 'html'
            | 'list'
            | 'paragraph'
            | 'table'
            | 'text'
            | 'thematicBreak'
            | 'yaml'
            | string;
    }
}
