/** @public */
export const FileExtension = {
    _3gp: '3gp',
    avif: 'avif',
    bmp: 'bmp',
    canvas: 'canvas',
    flac: 'flac',
    gif: 'gif',
    jpeg: 'jpeg',
    jpg: 'jpg',
    m4a: 'm4a',
    md: 'md',
    mkv: 'mkv',
    mov: 'mov',
    mp3: 'mp3',
    mp4: 'mp4',
    oga: 'oga',
    ogg: 'ogg',
    ogv: 'ogv',
    opus: 'opus',
    pdf: 'pdf',
    png: 'png',
    svg: 'svg',
    wav: 'wav',
    webm: 'webm',
    webp: 'webp'
} as const;
